### ISSUE TITLE
delegation not supported for subnet part

### ISSUE THREAD

**Issue by AnBenn** [T-Systems-MMS/terraform-azurerm-network#3]
as discussed:
  # module.network.azurerm_subnet.subnet["db"] will be updated in-place
  ~ resource "azurerm_subnet" "subnet" {
        id                                             = "/subscriptions/4c1b10e8-7301-4c93-84d7-045c20f11c20/resourceGroups/rg-buderus-dev/providers/Microsoft.Network/virtualNetworks/vnet-buderus-dev/subnets/snet-buderus-dev-db"
        name                                           = "snet-buderus-dev-db"
        # (8 unchanged attributes hidden)

      + delegation {
          + name = "fs"

          + service_delegation {
              + actions = [
                  + "Microsoft.Network/virtualNetworks/subnets/join/action",
                ]
              + name    = "Microsoft.DBforMySQL/flexibleServers"
            }
        }
    }

**Comment by hegessne** [comment]
Hi, wie ist hier der Status?

**Comment by mikaEz** [comment]
#4
